name: Cypress tests
on:
    pull_request:
        branches:
            - '*'
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            - name: Save Test Results
              uses: actions/upload-artifact@v2
              with:
                  name: test-results
                  path: cypress/report/
            - uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  cache: 'yarn'
            - name: Install dependecies
              run: yarn

            - name: Start server in the background
              run: yarn watch:dev &

            # Cypress has its own package.json in folder "e2e"
            - name: Install Cypress and run tests
              uses: cypress-io/github-action@v5
